runtime: php55
api_version: 1

handlers:
- url: /
  script: index.php

- url: /index\.html
  script: index.php

- url: /assets
  static_dir: assets

- url: /(.*\.(gif|png|jpg))$
  static_files: assets/\1
  upload: assets/.*\.(gif|png|jpg)$

- url: /admin/.*
  script: index.php
  login: index

- url: /.*
  script: index.php